
INPUT_DIR  = "input"
OUTPUT_DIR = "output"

#ссылки
METADATA_URL = "https://storage.yandexcloud.net/students-common/mass_spec_results.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YCAJELqVUR2I4aFR9yju0lZmQ%2F20251129%2Fru-central1%2Fs3%2Faws4_request&X-Amz-Date=20251129T075802Z&X-Amz-Expires=2592000&X-Amz-Signature=8696243c988ba07aaf3b8c3bbf6ef9eedaff7c5d6e4364aea6087493c19e3e39&X-Amz-SignedHeaders=host&response-content-disposition=attachment"

MS_URL       = "https://storage.yandexcloud.net/students-common/sample_metadata.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YCAJELqVUR2I4aFR9yju0lZmQ%2F20251129%2Fru-central1%2Fs3%2Faws4_request&X-Amz-Date=20251129T075822Z&X-Amz-Expires=2592000&X-Amz-Signature=10e1273d1fcbd5cba59ca00125eb26a4406c14a0ce39c97bcdd5a266493e8015&X-Amz-SignedHeaders=host&response-content-disposition=attachment"

# Пути к входным файлам (после скачивания)

METADATA_FILE = f"{INPUT_DIR}/sample_metadata.csv"
MS_FILE       = f"{INPUT_DIR}/mass_spec_results.csv"

# Пути к выходным файлам (3 антиджойна)

ONLY_META_FILE = f"{OUTPUT_DIR}/only_in_metadata.csv"
ONLY_MS_FILE   = f"{OUTPUT_DIR}/only_in_mass_spec.csv"
SYMM_DIFF_FILE = f"{OUTPUT_DIR}/symmetric_diff.csv"


rule all:
    input:
        ONLY_META_FILE,
        ONLY_MS_FILE,
        SYMM_DIFF_FILE


rule download_metadata:
    output:
        METADATA_FILE
    shell:
        """
        mkdir -p {INPUT_DIR}
        curl -L "{METADATA_URL}" -o {output}
        """

rule download_mass_spec:
    output:
        MS_FILE
    shell:
        """
        mkdir -p {INPUT_DIR}
        curl -L "{MS_URL}" -o {output}
        """


# 3 антиджойна 

rule antijoins:
    input:
        metadata = METADATA_FILE,
        ms       = MS_FILE
    output:
        only_meta = ONLY_META_FILE,
        only_ms   = ONLY_MS_FILE,
        symm_diff = SYMM_DIFF_FILE
    shell:
        """
        mkdir -p {OUTPUT_DIR}
        python - << 'EOF'
import pandas as pd

metadata_path = "{input.metadata}"
ms_path       = "{input.ms}"

only_meta_path = "{output.only_meta}"
only_ms_path   = "{output.only_ms}"
symm_path      = "{output.symm_diff}"

key = "sample_id" 

meta = pd.read_csv(metadata_path)
ms   = pd.read_csv(ms_path)

# 1) антиджойн: строки, которые есть только в metadata
only_meta = meta[~meta[key].isin(ms[key])]
only_meta.to_csv(only_meta_path, index=False)

# 2) антиджойн: строки, которые есть только в mass_spec
only_ms = ms[~ms[key].isin(meta[key])]
only_ms.to_csv(only_ms_path, index=False)

# 3) симметрическая разность (уникальные и там, и там)
symm = pd.concat([only_meta, only_ms], ignore_index=True)
symm.to_csv(symm_path, index=False)
EOF
        """
